Repository openshift/hypershift-dataplane-metrics-forwarder, pull requests merged in 2023-02, with the labels that each got.

#3 Metrics forwarder pko setup
  README.md
  build/Dockerfile
  dataplane-policy.yaml
  hcp-policy.yaml
  package/manifest.yaml
  package/resources.yaml.gotmpl
Labels: lgtm, tide/merge-method-squash, approved

#2 Add GitHub pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  OWNERS
Labels: lgtm, approved

#4 OSD-15268: Setup continuous deployment
  Makefile
  build/Dockerfile
  build/build_deploy.sh
  build/build_push.sh
  dataplane-policy.yaml
  hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
  hcp-policy.yaml
Labels: lgtm, jira/valid-reference, approved

#5 Change bash scripts permissions
  build/Dockerfile
  build/build_deploy.sh
  build/build_push.sh
Labels: lgtm, approved

#6 Change compliance type for CMO config
  hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
Labels: lgtm, approved

#7 Fix faulty indentation
  hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
Labels: lgtm, approved

#8 Fix name conflict between the proxy and the cnofig
  hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
Labels: lgtm, approved

#9 Add explicit conditions
  hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
Labels: lgtm, approved

#10 Fix object-template indentation
  hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
Labels: lgtm, approved
